<?php

namespace AppBundle\Repository;

/**
 * AvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvionRepository extends \Doctrine\ORM\EntityRepository
{
}
