<?php

namespace AppBundle\Repository;

/**
 * diaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaRepository extends \Doctrine\ORM\EntityRepository
{
}
