<?php

namespace AppBundle\Repository;

/**
 * HorarioDeshabilitadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioDeshabilitadoRepository extends \Doctrine\ORM\EntityRepository
{
}
