<?php

namespace AppBundle\Repository;

/**
 * PilotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilotoRepository extends \Doctrine\ORM\EntityRepository
{
}
