<?php

namespace AppBundle\Repository;

/**
 * PilotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PilotoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllWithUser()
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select('p, u')
		   ->from('AppBundle:Piloto', 'p')
		   ->leftJoin('p.usuario', 'u');
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
