<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Request;

/**
 * TurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNotUser(User $user)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->from('AppBundle:Turno', 'u')
            ->where('t.user != :user')
            ->setParameter('user', $user);
        return $qb->getQuery()->getResult();
    }
}
