<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Turno;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * TurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoRepository extends EntityRepository
{
    /**
     * @param User $user
     * @param \DateTime $start
     * @param \DateTime $end
     * @return array
     */
    public function findByNotUser(User $user, \DateTime $start, \DateTime $end)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(['t'])
            ->from('AppBundle:Turno', 't')
            ->where('t.user != :user')
            ->andWhere('t.fecha between :start and :end')
            ->setParameter(':start', $start->format('Y-m-d H:i:s'))
            ->setParameter(':end', $end->format('Y-m-d H:i:s'))
            ->setParameter('user', $user);
        return $qb->getQuery()->getResult();
    }

    /**
     * @param Turno $turno
     * @param User $user
     * @return array
     */
    public function findByUserAndDate(Turno $turno, User $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t')
            ->from(Turno::class, 't')
            ->where("t.fecha like :fecha")
            ->andWhere($qb->expr()->eq('t.user', $user->getId()))
            ->setParameter('fecha', $turno->getFecha()->format('Y-m-d') . '%');
        return $qb->getQuery()->getArrayResult();
    }

    /**
     * @param \DateTime $start
     * @param \DateTime $end
     * @return array
     */
    public function findByDateRange(\DateTime $start, \DateTime $end)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(['t'])
            ->from('AppBundle:Turno', 't')
            ->where('t.fecha between :start and :end')
            ->setParameter(':start', $start->format('Y-m-d H:i:s'))
            ->setParameter(':end', $end->format('Y-m-d H:i:s'));
        return $qb->getQuery()->getResult();
    }
}
