<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRole($role)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select(['u', 'd'])
            ->from('AppBundle:User', 'u')
            ->innerJoin('u.userData', 'd')
            ->where('u.roles like :role')
            ->setParameter('role', '%'.$role.'%');

        return $qb->getQuery()->getResult();
    }

    public function findAll()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(['u', 'd'])
            ->from('AppBundle:User', 'u')
            ->innerJoin('u.userData', 'd');

        return $qb->getQuery()->getResult();
    }

    public function findAllUsers()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select(['u', 'd'])
            ->from('AppBundle:User', 'u')
            ->innerJoin('u.userData', 'd')
            ->where('u.roles not like :role')
            ->setParameter('role', '%ADMIN%');

        return $qb->getQuery()->getResult();
    }
}
