# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_PILOT: ROLE_PILOT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: BackendHomepage

            logout:
                path: fos_user_security_logout
                target: BackendHomepage
            
            anonymous:    true

    access_control:
        - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/, role: ROLE_ADMIN }