# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.request.listener:
    class: AppBundle\EventListener\RequestListener
    arguments: [ "@app.log" ]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  app.log:
    class: AppBundle\Services\LogService
    arguments: [ "@doctrine.orm.entity_manager" ]